import {test} from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';
import {initCollaboration,collaborationRoute,proposeFromText,allowed} from '../worker/collaboration.js';
function setup(){const db=new DatabaseSync(':memory:');db.exec(`CREATE TABLE users(id TEXT PRIMARY KEY,name TEXT,mode TEXT);CREATE TABLE rooms(id TEXT PRIMARY KEY,uid TEXT,title TEXT,created REAL);CREATE TABLE turns(id TEXT PRIMARY KEY,uid TEXT,room TEXT,fingerprint TEXT,text TEXT,image BLOB,image_type TEXT,mode TEXT,status TEXT,created REAL);INSERT INTO users VALUES('a','지은','expert'),('b','엄마','easy'),('c','외부인','guided');INSERT INTO rooms VALUES('private','a','나의 방',1);INSERT INTO turns VALUES('private-turn','a','private','fp','비밀 내용',X'FFD8FF','image/jpeg','easy','message',1);`);const s={run(q,...p){p.length?db.prepare(q).run(...p):db.exec(q);},rows(q,...p){return db.prepare(q).all(...p);},one(q,...p){return db.prepare(q).get(...p);},limit(){},ctx:{storage:{transactionSync(fn){db.exec('BEGIN');try{fn();db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}}}}};initCollaboration(s);async function call(uid,path,method='GET',b={}){try{const r=await collaborationRoute(s,new Request('https://app.example'+path,{method}),{uid,b});return {status:r?.status,data:r?await r.json():null};}catch(e){return {status:e.status||500,data:{detail:e.message}};}}return {s,call};}
async function family(call){const g=await call('a','/api/groups','POST',{title:'우리 가족'});assert.equal(g.status,201);const room=g.data.id;const invite=await call('a',`/api/rooms/${room}/invite`,'POST');assert.equal((await call('b','/api/invitations/claim','POST',{code:invite.data.code})).status,200);return room;}
const create=(call,room,extra={})=>call('a','/api/agenda','POST',{request_id:crypto.randomUUID(),room,kind:'event',title:'서울역 모임',starts:'2026-10-03T02:00:00Z',place:'3번 출구',...extra});
test('Invitation is single use; only owner invites; members cannot read private room',async()=>{const {s,call}=setup();const room=await family(call);assert.equal(!!allowed(s,room,'b'),true);assert.equal(!!allowed(s,'private','b'),false);assert.equal((await call('b',`/api/rooms/${room}/invite`,'POST')).status,403);const v=await call('a',`/api/rooms/${room}/invite`,'POST');await call('b','/api/invitations/claim','POST',{code:v.data.code});assert.equal((await call('c','/api/invitations/claim','POST',{code:v.data.code})).status,400);});
test('Agenda ownership, confirmations, task acceptance and completion stay separate',async()=>{const {call}=setup(),room=await family(call);const a=await create(call,room,{kind:'task',assignee:'b'});assert.equal(a.status,201);const key=a.data.id;assert.equal((await call('b',`/api/agenda/${key}/complete`,'POST',{done:true})).status,403);assert.equal((await call('b',`/api/agenda/${key}/confirm`,'POST',{version:1})).status,200);assert.equal((await call('b',`/api/agenda/${key}/accept`,'POST')).status,200);assert.equal((await call('a',`/api/agenda/${key}/complete`,'POST',{done:true})).status,403);assert.equal((await call('b',`/api/agenda/${key}/complete`,'POST',{done:true})).data.done,1);assert.deepEqual((await call('c','/api/agenda')).data,[]);});
test('Approved changes propagate offsets, invalidate confirmations, preserve completed tasks and reject stale proposals',async()=>{const {call}=setup(),room=await family(call);const a=(await create(call,room)).data;const child=(await create(call,room,{kind:'task',title:'준비',assignee:'a',parent:a.id,offset:-30})).data;await call('a',`/api/agenda/${child.id}/complete`,'POST',{done:true});await call('b',`/api/agenda/${a.id}/confirm`,'POST',{version:1});const change=await call('b',`/api/agenda/${a.id}/changes`,'POST',{version:1,patch:{starts:'2026-10-03T03:00:00Z'}});assert.equal((await call('b',`/api/changes/${change.data.id}/approve`,'POST')).status,403);assert.equal((await call('a',`/api/changes/${change.data.id}/approve`,'POST')).status,200);const list=(await call('a','/api/agenda')).data;const result=list.find(x=>x.id===child.id);assert.equal(result.starts,'2026-10-03T02:30:00.000Z');assert.equal(result.done,1);assert.equal(list.find(x=>x.id===a.id).confirmations.length,0);assert.equal((await call('a',`/api/changes/${change.data.id}/approve`,'POST')).status,409);assert.equal((await call('b','/api/notices')).data.length>0,true);});
test('Help shares only chosen text and optional image, without exposing private source; only requester resolves',async()=>{const {s,call}=setup(),room=await family(call);const request_id=crypto.randomUUID();const b={room,request_id,title:'TV 도움',text:'선택한 설명',source:'private-turn',share_image:false};assert.equal((await call('a','/api/help','POST',b)).status,201);assert.equal(s.one('SELECT image FROM turns WHERE id=?',request_id).image,null);assert.equal(s.one('SELECT text FROM turns WHERE id=?',request_id).text.includes('비밀'),false);assert.equal((await call('a','/api/help','POST',b)).status,200);const photoId=crypto.randomUUID();assert.equal((await call('a','/api/help','POST',{...b,request_id:photoId,share_image:true})).status,201);assert.ok(s.one('SELECT image FROM turns WHERE id=?',photoId).image);assert.equal((await call('b',`/api/help/${request_id}/resolve`,'POST')).status,403);assert.equal((await call('a',`/api/help/${request_id}/resolve`,'POST')).status,200);assert.equal((await call('c','/api/help')).data.length,0);});
test('Preferences persist per user and proposal parser leaves dates for confirmation',async()=>{const {call}=setup();assert.equal((await call('a','/api/preferences','PUT',{font:'larger',speech:.7})).status,200);assert.equal((await call('b','/api/preferences')).data.font,'normal');assert.equal(proposeFromText('토요일 오후 1시에 만나자').time,'13:00');assert.equal(proposeFromText('토요일 오후 1시에 만나자').date,null);assert.equal(proposeFromText('안녕'),null);});

test('One source message creates one shared agenda item; later saves return it without overwriting',async()=>{
 const {s,call}=setup(),room=await family(call);s.run("INSERT INTO turns VALUES('shared-source','a',?,'fp','토요일 오전 11시 서울역에서 만나자',NULL,NULL,'easy','message',1)",room);
 const first=await create(call,room,{source:'shared-source'});assert.equal(first.status,201);
 const again=await call('b','/api/agenda','POST',{request_id:crypto.randomUUID(),room,source:'shared-source',kind:'event',title:'다른 제목',place:''});assert.equal(again.status,200);assert.equal(again.data.id,first.data.id);assert.equal(again.data.title,'서울역 모임');assert.equal(s.one('SELECT count(*) AS n FROM agenda WHERE source=?','shared-source').n,1);
 assert.equal((await call('b',`/api/agenda/${first.data.id}`)).status,200);assert.equal((await call('c',`/api/agenda/${first.data.id}`)).status,404);
});
test('Detail exposes approved changes and only confirmations for the current version',async()=>{
 const {call}=setup(),room=await family(call),a=(await create(call,room)).data;
 await call('b',`/api/agenda/${a.id}/confirm`,'POST',{version:1});
 const c=(await call('a',`/api/agenda/${a.id}/changes`,'POST',{version:1,patch:{starts:'2026-10-03T03:00:00Z'}})).data;
 await call('a',`/api/changes/${c.id}/approve`,'POST');
 const detail=(await call('b',`/api/agenda/${a.id}`)).data;assert.equal(detail.version,2);assert.equal(detail.confirmations.length,0);assert.equal(detail.latest_change.before.starts,a.starts);assert.equal(detail.latest_change.after.starts,'2026-10-03T03:00:00.000Z');assert.equal(detail.latest_change.actor_name,'지은');
});
test('Place candidates are literal and weekdays remain unassigned dates',()=>{
 const candidate=proposeFromText('토요일 오전 11시에 서울역 3번 출구에서 만나요');assert.equal(candidate.place,'서울역 3번 출구');assert.equal(candidate.date,null);assert.equal(proposeFromText('오후 1시에 만나자').place,'');
});

test('Candidate title omits the separate weekday and clock fields',()=>{assert.equal(proposeFromText('토요일 오전 11시에 서울역에서 만나요.').title,'서울역에서 만나요.');});
